# Generated by Django 5.2.1 on 2025-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('wanted_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer', models.CharField(max_length=255)),
                ('projects', models.TextField()),
                ('deal', models.CharField(max_length=20)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('offers', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('kwork_id', models.PositiveIntegerField()),
            ],
        ),
    ]
