# Generated by Django 5.2.1 on 2025-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='last_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offers',
            field=models.PositiveIntegerField(),
        ),
    ]
