# Generated by Django 5.2.1 on 2025-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_offers_buyer_alter_offers_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
