# Generated by Django 5.2.1 on 2025-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_offers_created_at_offers_status_offers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('interesting', 'Интересно'), ('not_interesting', 'Не интересно')], default='new', max_length=20, null=True),
        ),
    ]
