# Generated by Django 5.2.1 on 2025-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_offers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
