# Generated by Django 5.2.1 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_alter_offers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='projects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
